### PR TITLE
Additional keywords

### PR DESCRIPTION
**Pull request by Righolt**
I added some additional keywords for a VS Code extension implementation that might be worthwhile to be added here as well.

### CODE REVIEW

**Comment by rpardee** [comment]
Thanks very much for looking at this!

If I'm understanding it, this would take a fair number of function names (lowcase, substr, etc.) and change them from support.function.sas scope to keyword.other.sas scope.  Is that right?

**Comment by Righolt** [comment]
There are 2 additions:

1. Macro terms starting with % are expanded.
1. Some keywords are added, the way they are colored might be different between VS Code and sublime. I did not explicitly take them out of any category, I based it on what was not explicitly included in the prior list AND a list of keywords from another highlighting scheme (for Notepad++) a colleague developed AND what was not highlighting for me in VS code (although I did not check every single one of them).

Some of the terms, did highlight as a function, but not when used differently. I did not actually remove any the previous declarations.

**Comment by Righolt** [comment]
@rpardee Did you have any follow up questions for me? Cheers.

**Comment by rpardee** [comment]
Sorry to let this go--no more questions.  I need to bone up on my git skillz so I can take the new syntax for a test drive before merging.  My primary constituency is sublime users, so I want to make sure it's a win there.  I'll take a look now.

**Comment by Righolt** [comment]
Yeah, I haven't tested it in sublime, but figure sharing after stealing wouldn't hurt.

**Comment by rpardee** [comment]
All righty--looks like I had the power all along--just had to click on the 'command line' link in the merge box above for a nice list of commands that let me create a test branch & pull your changes into it.

I don't see a discernible difference in coloring, so I'm merging it.  Thanks very much for contributing!

**Comment by Righolt** [comment]
I'm happy to help.

**Pull request merged**
